// Generated by aidef. Edit compiler.aid to change behavior.
export const DEFAULT_WHITELIST: string[] = ['bun init', 'bun install', 'bun add'];

export function isAllowed(command: string, customWhitelist?: string[]): boolean {
  if (DEFAULT_WHITELIST.includes(command)) {
    return true;
  }

  if (customWhitelist && customWhitelist.includes(command)) {
    return true;
  }

  return false;
}
