// Generated by aidef. Edit compiler.aid to change behavior.

export interface LogEntry {
  timestamp: string;
  type: 'ai_call' | 'command_execution' | 'file_write';
  leafPath: string;
  details: any;
}

export interface Logger {
  log: (entry: Omit<LogEntry, 'timestamp'>) => void;
}

export function createLogger(logFilePath: string): Logger {
  return {
    log: async (entry: Omit<LogEntry, 'timestamp'>) => {
      const timestamp = new Date().toISOString();
      const logEntryWithTimestamp: LogEntry = { ...entry, timestamp };
      const logLine = JSON.stringify(logEntryWithTimestamp) + '\n';

      try {
        await Bun.write(logFilePath, logLine, { append: true });
      } catch (error) {
        console.error(`Failed to write to log file ${logFilePath}:`, error);
      }
    },
  };
}
