// Generated by aidef. Edit runtime.aid to change behavior.
import * as fs from 'node:fs';
import { dirname } from 'node:path';

export interface LogEntry {
  timestamp: string;
  type: 'ai_call' | 'command_execution' | 'file_write' | 'error';
  leafPath: string;
  details: any;
}

export interface Logger {
  log(entry: Omit<LogEntry, 'timestamp'>): void;
}

export function createLogger(logFilePath: string): Logger {
  // Ensure the parent directory of logFilePath exists
  fs.mkdirSync(dirname(logFilePath), { recursive: true });

  return {
    log(entry: Omit<LogEntry, 'timestamp'>): void {
      const timestamp = new Date().toISOString();
      const fullEntry: LogEntry = { ...entry, timestamp };
      const logLine = JSON.stringify(fullEntry) + '\n';
      // Append the JSON line to the logFilePath
      fs.appendFileSync(logFilePath, logLine);
    },
  };
}
