// Generated by aidef. Edit extract.aid to change behavior.
import type { ScanResult } from './scanner';
import type { ModuleInfo, ProjectAnalysis } from './analyzer';
import type { LLMProvider } from '../providers/types';

export interface AidOutput {
  rootAid: string;
  includes: Map<string, string>;
}

function formatModuleInfo(module: ModuleInfo, indent: string = ''): string {
  let result = `${indent}- Module: ${module.name}\n`;
  result += `${indent}  Path: ${module.path}\n`;
  result += `${indent}  Description: ${module.description}\n`;
  if (module.keyExports && module.keyExports.length > 0) {
    result += `${indent}  Key Exports: ${module.keyExports.join(', ')}\n`;
  }
  if (module.children && module.children.length > 0) {
    result += `${indent}  Children:\n`;
    for (const child of module.children) {
      result += formatModuleInfo(child, indent + '    ');
    }
  }
  return result;
}

export async function generateAid(analysis: ProjectAnalysis, scanResult: ScanResult, provider: LLMProvider): Promise<AidOutput> {
  let modulesDescription = '';
  for (const module of analysis.modules) {
    modulesDescription += formatModuleInfo(module);
  }

  const prompt = `You are an AI assistant that generates .aid files for software projects.
Your task is to create a high-level architectural description of a project in the .aid format.
The output should be a JSON object with two fields:
- \`rootAid\`: A string containing the content of the main \`root.aid\` file.
- \`includes\`: An object where keys are filenames (e.g., "module_name.aid") and values are strings containing the content of those include files.

Follow these rules for generating the .aid content:
1.  **Top-level Prose**: Start with a general description of the project.
2.  **Module Blocks**: Use \`module "ModuleName" { ... }\` syntax.
3.  **Path Parameter**: Inside module blocks, use \`path="relative/path/to/module"\` for the main file/directory of the module.
4.  **Nested Modules**: Represent sub-modules as nested module blocks.
5.  **Include Statements**: If the project has 5 or more top-level modules, split major modules into separate include files. In \`root.aid\`, use \`include "filename.aid"\` to reference them. The content of these included files should be placed in the \`includes\` object.
6.  **Content**: Describe WHAT the module does, not HOW it does it. Keep it abstract and descriptive, NOT code.
7.  **Preserve Specifics**: Include important details like package names, API patterns, model names, and port numbers.
8.  **JSON Format**: Ensure the entire output is a valid JSON object.

Here is the project analysis:
Project Name: ${analysis.projectName}
Description: ${analysis.description}
Language: ${analysis.language}
Runtime: ${analysis.runtime}
Dependencies: ${analysis.dependencies.join(', ')}

Modules:
${modulesDescription}

File Scan Summary:
Total Files: ${scanResult.totalFiles}
Total Bytes: ${scanResult.totalBytes}

Generate the JSON output.`;

  const response = await provider.generate({
    messages: [{ role: 'user', text: prompt }],
    temperature: 0.3,
  });

  const text = response.text || '';

  let parsedOutput: { rootAid: string; includes: { [key: string]: string } };
  try {
    parsedOutput = JSON.parse(text);
  } catch (error) {
    console.error('Failed to parse LLM response as JSON:', error);
    console.error('LLM response:', text);
    // Fallback: if parsing fails, assume the LLM just returned rootAid content
    return {
      rootAid: text,
      includes: new Map<string, string>()
    };
  }

  return {
    rootAid: parsedOutput.rootAid,
    includes: new Map(Object.entries(parsedOutput.includes || {}))
  };
}
