// Generated by aidef. Edit extract.aid to change behavior.
import { GoogleGenAI } from '@google/genai';
import type { ProjectFile, ScanResult } from './scanner';

export interface ModuleInfo {
  name: string;
  path: string;
  description: string;
  children: ModuleInfo[];
  keyExports: string[];
}

export interface ProjectAnalysis {
  projectName: string;
  description: string;
  language: string;
  runtime: string;
  modules: ModuleInfo[];
  dependencies: string[];
}

export async function analyze(scanResult: ScanResult, apiKey: string): Promise<ProjectAnalysis> {
  const genai = new GoogleGenAI({ apiKey });

  let fileSummary = '';
  const keyFileContents: { [key: string]: string } = {};
  const relevantFileNames = ['package.json', 'tsconfig.json', 'README.md', 'index.ts', 'main.ts', 'app.ts'];

  for (const file of scanResult.files) {
    fileSummary += `- ${file.relativePath} (${file.sizeBytes} bytes): ${file.content.split('\\n')[0].substring(0, 100)}\\n`;
    if (relevantFileNames.includes(file.relativePath)) {
      keyFileContents[file.relativePath] = file.content;
    }
  }

  let keyFilesPrompt = '';
  for (const fileName in keyFileContents) {
    keyFilesPrompt += `\\n--- Content of ${fileName} ---\\n\`\`\`\\n${keyFileContents[fileName]}\\n\`\`\`\\n`;
  }

  const prompt = `
You are an expert software project analyzer. Your task is to analyze a given project structure and its files to provide a comprehensive ProjectAnalysis in JSON format.

Here is a summary of the project files:
${fileSummary}

Here are the contents of some key files:
${keyFilesPrompt}

Please provide a ProjectAnalysis object in JSON format, adhering to the following TypeScript interfaces:

interface ModuleInfo {
  name: string;
  path: string;
  description: string;
  children: ModuleInfo[];
  keyExports: string[];
}

interface ProjectAnalysis {
  projectName: string;
  description: string;
  language: string;
  runtime: string;
  modules: ModuleInfo[];
  dependencies: string[];
}

A "module" is a cohesive group of files that serve a single purpose, often corresponding to a directory. Not every file is a module; files within a directory usually form one module together. Identify natural module boundaries.

Ensure the JSON output is valid and directly parsable. Do not include any additional text or formatting outside the JSON object.
`;

  const response = await genai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    config: { temperature: 0 }
  });

  const text = response.text;
  // The LLM might sometimes include markdown code block delimiters, try to remove them.
  const jsonString = text.replace(/```json\\n?/, '').replace(/\\n?```/, '');

  try {
    const analysis: ProjectAnalysis = JSON.parse(jsonString);
    return analysis;
  } catch (error) {
    console.error('Failed to parse LLM response as JSON:', error);
    console.error('LLM response:', jsonString);
    throw new Error('Could not parse project analysis from LLM response.');
  }
}
