// Generated by aidef. Edit extract.aid to change behavior.
import { scan, ScanResult } from './scanner';
import { analyze, ProjectAnalysis } from './analyzer';
import { generateAid } from './aidGenerator';
import * as path from 'node:path';
import * as fs from 'node:fs/promises';

export async function extract(targetPath: string, outputFile: string, apiKey: string): Promise<void> {
  const scanResult = await scan(targetPath);
  const projectAnalysis = await analyze(scanResult, apiKey);
  const aidOutput = await generateAid(projectAnalysis, scanResult, apiKey);

  const outputDir = path.dirname(outputFile);
  await fs.mkdir(outputDir, { recursive: true });

  await Bun.write(outputFile, aidOutput.rootAid);

  for (const [filename, content] of aidOutput.includes.entries()) {
    const includeFilePath = path.join(outputDir, filename);
    await Bun.write(includeFilePath, content);
  }
}
