// Generated by aidef. Edit compiler.aid to change behavior.
import { HumanCompiler } from './resolver';
import { GenCompiler } from './gen';
import type { LLMProvider } from '../providers/types';

export async function compile(rootFile: string, outputDir: string, provider: LLMProvider): Promise<void> {
  const resolver = new HumanCompiler(outputDir);
  const resolvedPath = await resolver.compile(rootFile);
  
  const genCompiler = new GenCompiler(provider);
  await genCompiler.compile(resolvedPath);
}
