// Generated by aidef. Edit compiler.aid to change behavior.
import { HumanCompiler } from './resolver';
import { GenCompiler } from './gen';

export async function compile(rootFile: string, outputDir: string, apiKey: string): Promise<void> {
  const resolver = new HumanCompiler(outputDir);
  const resolvedPath = await resolver.compile(rootFile);
  
  const genCompiler = new GenCompiler(apiKey);
  await genCompiler.compile(resolvedPath);
}
