// Generated by aidef. Edit compiler.aid to change behavior.
import * as fs from 'node:fs';

export interface CompileLogEntry {
  timestamp: string;
  type: string;
  nodePath: string;
  details: any;
}

export interface Logger {
  log(type: string, nodePath: string, details: any): void;
  close(): void;
}

export function createCompileLogger(outputDir: string): Logger {
  fs.mkdirSync(outputDir, { recursive: true });
  const logFilePath = `${outputDir}/compile.log.jsonl`;
  const writer = Bun.file(logFilePath).writer({ append: true });

  return {
    log(type: string, nodePath: string, details: any): void {
      const entry: CompileLogEntry = {
        timestamp: new Date().toISOString(),
        type,
        nodePath,
        details,
      };
      writer.write(JSON.stringify(entry) + '\n');
    },
    close(): void {
      writer.flush();
      writer.end();
    },
  };
}
