// Generated by aidef. Edit root.aid to change behavior.

import * as path from 'path';
import * as fs from 'node:fs';

interface BrowseOptions {
  output: string;
  apiKey: string;
}

interface AnalysisIssue {
  type: 'miscommunication' | 'inefficiency' | 'slowResponse' | 'other';
  severity: 'low' | 'medium' | 'high' | 'critical';
  description: string;
  relatedNodeIds?: string[];
  suggestedFix?: string;
}

interface AnalysisReport {
  summary: string;
  issues: AnalysisIssue[];
  performanceMetrics: {
    totalCalls: number;
    failedCalls: number;
    avgDurationMs: number;
    maxDurationMs: number;
  };
}

interface Plan {
  planId: string;
  rootInstructionId: string;
  instructions: PlanInstruction[];
}

interface PlanInstruction {
  id: string;
  type: 'node' | 'leaf';
  name: string;
  description: string;
  generatedCodeSnippet: string;
  originalAidFile: string;
  originalAidLine: number;
  childrenIds?: string[];
}

interface TuiEvent {
  type: 'keyPress';
  key?: string;
}

interface Suggestion {
  id: string;
  description: string;
  targetFile: string;
  targetLine?: number;
  amendmentType: 'insert' | 'replace' | 'delete' | 'modify';
  amendmentContent: string;
  contextSnippet: string;
  status?: 'pending' | 'applied' | 'rejected';
}

async function loadPlanFiles(outputDir: string): Promise<Plan[]> {
  const plans: Plan[] = [];
  try {
    const files = fs.readdirSync(outputDir);
    for (const file of files) {
      if (file.startsWith('plan-') && file.endsWith('.json')) {
        const filePath = path.join(outputDir, file);
        const content = await Bun.file(filePath).text();
        plans.push(JSON.parse(content));
      }
    }
  } catch (error) {
    console.error(`Error loading plan files: ${error}`);
  }
  return plans;
}

async function loadAnalysisReports(outputDir: string): Promise<AnalysisReport[]> {
  const reports: AnalysisReport[] = [];
  try {
    const files = fs.readdirSync(outputDir);
    for (const file of files) {
      if (file.startsWith('analysis-report-') && file.endsWith('.json')) {
        const filePath = path.join(outputDir, file);
        const content = await Bun.file(filePath).text();
        reports.push(JSON.parse(content));
      }
    }
  } catch (error) {
    console.error(`Error loading analysis reports: ${error}`);
  }
  return reports;
}

function handleUserInteraction(event: TuiEvent): void {
  if (event.type === 'keyPress') {
    switch (event.key) {
      case 'q':
      case '\x03': // Ctrl+C
        console.log('Exiting TUI.');
        process.exit();
        break;
      case 'p':
        console.log('\n--- Displaying Plans (Placeholder) ---');
        break;
      case 'a':
        console.log('\n--- Displaying Analysis Reports (Placeholder) ---');
        break;
      default:
        console.log(`Key pressed: ${event.key} (unhandled)`);
        break;
    }
  }
}

export async function browse(options: BrowseOptions): Promise<void> {
  console.log(`Starting browse TUI for output directory: ${options.output}`);

  const planData = await loadPlanFiles(options.output);
  const analysisReports = await loadAnalysisReports(options.output);

  if (planData.length === 0 && analysisReports.length === 0) {
    console.warn('No plan files or analysis reports found. Exiting.');
    return;
  }

  console.log(`
========================================
  AI Development TUI - Browse Mode
========================================
`);
  console.log('Plans Found:');
  planData.forEach(plan => console.log(`  - Plan ID: ${plan.planId}`));
  console.log('\nAnalysis Reports Found:');
  analysisReports.forEach((report, index) => console.log(`  - Report ${index + 1}: ${report.summary}`));

  console.log(`
----------------------------------------
  (Press 'q' to quit, 'p' for plans, 'a' for analysis)
----------------------------------------
`);

  process.stdin.setRawMode(true);
  process.stdin.resume();
  process.stdin.setEncoding('utf8');

  process.stdin.on('data', (key: string) => {
    handleUserInteraction({ type: 'keyPress', key });
  });
}
