// Generated by aidef. Edit root.aid to change behavior.
import { Command } from 'commander';
import { compile } from './compiler';
import { run } from './runtime';

const program = new Command();

// Get GEMINI_API_KEY
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
if (!GEMINI_API_KEY) {
  console.error('Error: GEMINI_API_KEY is not set. Please set the environment variable.');
  process.exit(1);
}

// Global options
program
  .option('-o, --output <path>', 'Output directory', `/tmp/aidef-${Date.now()}`)
  .option('--max-parallel <number>', 'Maximum parallel operations', '10')
  .option('--max-retries <number>', 'Maximum retries for operations', '3')
  .option('--max-depth <number>', 'Maximum depth for compilation/analysis', '5');

// Compile command
program
  .command('compile [file]')
  .description('Compile an AIDL file')
  .argument('[file]', 'Root AIDL file to compile', 'root.aid')
  .action(async (file) => {
    const opts = program.opts(); // Get global options
    const outputDir = opts.output;
    console.log(`Compiling ${file} to ${outputDir}...`);
    console.log(`Max parallel: ${opts.maxParallel}, Max retries: ${opts.maxRetries}, Max depth: ${opts.maxDepth}`);
    try {
      await compile(file, outputDir, GEMINI_API_KEY);
      console.log('Compilation successful.');
    } catch (error) {
      console.error('Compilation failed:', error);
      process.exit(1);
    }
  });

// Run command
program
  .command('run')
  .description('Run the compiled AIDL output')
  .action(async () => {
    const opts = program.opts(); // Get global options
    const outputDir = opts.output;
    console.log(`Running from ${outputDir}...`);
    try {
      await run(outputDir, GEMINI_API_KEY);
      console.log('Run successful.');
    } catch (error) {
      console.error('Run failed:', error);
      process.exit(1);
    }
  });

// Analyse command (not yet implemented)
program
  .command('analyse')
  .description('Analyse the AIDL project (not yet implemented)')
  .action(() => {
    console.log('Analyse command is not yet implemented.');
  });

// Browse command (not yet implemented)
program
  .command('browse')
  .description('Browse the AIDL project (not yet implemented)')
  .action(() => {
    console.log('Browse command is not yet implemented.');
  });

program.parse(process.argv);
